name: Scheduled Tweet
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Runs at 4:40 AM UTC every day
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Call Tweet API endpoint
        run: |
          curl -X GET \
          -H "Content-Type: application/json" \
          https://backend-twitter-xi.vercel.app/cron/post-news-tweet/