name: Scheduled Tweet
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Call Tweet API endpoint
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_JOB_API_KEY }}" \
          -H "Content-Type: application/json" \
          https://backend-twitter-xi.vercel.app/cron/post-news-tweet